name: CI04
on: workflow_dispatch

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: pre - checkout
        run: |
          pwd
          ls -lh
      - name: checkout code
        uses: actions/checkout@v3
        with:
          repository: xiaopeng163/github-actions-python
      - name: after -checkout
        run: |
          pwd
          ls -lh
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
